Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false
