Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Next:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
